### ISSUE TITLE
Impure backend implementation

### ISSUE THREAD

**Issue by Tantalus13A98B5F** [Kraks/sai#23]
First commit [here](https://github.com/Kraks/sai/commit/93c0f89abc12210a795fcd1c574f24177a6061a2).

Basic idea is to use rvalue ref `std::move(*this)` as a replacement for returning new objects, so that it can (in the future) work with the current user code in the form of `SS x123 = x234.some_act(...`

Revisions on major data structures are done, but interfaces are still incompatible with some user code, especially when they assumed the use of *immer*.

**Comment by Tantalus13A98B5F** [comment]
- [ ] `llsc_external.hpp` incompatible
- [ ] `sym_exec_br` incompatible (forking not implemented)
- [ ] `llsc_main` from KMP case incompatible

**Comment by Kraks** [comment]
That's a good start! A few comments:

- If those methods return `move(*this)`, then the original object may not be "valid" any more. Consider this example:

```
std::map<Id, PtrVal> m = {{0, make_IntV(-1)}};
Frame f1(m);
Frame f2 = f1.assign(0, make_IntV(42));
// now f2.env.size() is 1 but f1.env is empty
```

  To generate correct programs, this essentially requires that the staged interpreter in Scala is either carefully written in a way that respects the move semantics/affinity after any effectful operation, or the metaprogramming system (ie LMS here) is able to reason and respect the move semantics (which means, to prevent generating programs that reuse the old object after any effectful operation on it). So far, we _seem_ to meet the first requirement since the staged program is written with a state monad... But I'm not sure if it is indeed the case for all kinds of code we generated. And since C++ won't statically check use-after-move, it might be very tricky to debug.

  One of the other potential issues I can see here is to generate correct code that mixes different ways of calling `assign`, for example:

```
Frame f1({});
Frame f2 = f1.assign(0, a); // move constructor called
f1.assign(0, b); // move constructor not called
// now f2 holds value `0 -> a` but f1 holds value `0 -> b`
```

  Or, we could generate code like `Frame&& f2 = f1.assign(...)`, then move constructor is not called. The caveat here is that `f2` and `f1` are aliased but in the metaprogram we don't know that, and it seems to require our "reachability types" to be implemented in the system. The other option is to return `*this` of type `&T`, and the call-site will be `Frame& f2 = ...`, but this induces aliases as well.

- Maybe it is a good idea to have "backend-agnostic" code generation eventually, and in the reachability types/graph IR paper we designed type systems that can exactly deal with aliases and move semantics when generating code.

  But at the moment I'm not sure if baking ownership transfer semantics in these operations will complicate other parts of the generated code, and more importantly, we don't need to stick with the functional interface, which means (most?) effectful methods can just return `void`. The metaprogram/compiler for the current short-term effort is supposed to generate code that is compatible with that. 

- ps: the default move constructor seems to be just `move`ing every field.
